### PR TITLE
clarify that missing road may trigger this

### PR DESCRIPTION
**Pull request by matkoniecz**
addresses (partially) #29

it would be nice to mention how far away road needs to be to trigger this in description
maybe in an extra section is listing parameters

NOTE: untested code

### CODE REVIEW

**Comment by lonvia** [comment]
Apologies for commenting too late: the additional description is fine but I would prefer to keep the titles short. And titles with an 'or' in them are confusing to read. Okay, if I revert just the change of the title?

**Comment by matkoniecz** [comment]
`addr:street without road match`? `addr:street without match`? `addr:street without street`?

The problem is that old name suggested/claimed that `addr:street` is wrong, while problem may be with road.

**Comment by lonvia** [comment]
But there was a road match. There always is a road match. The symptom is that the name of the road that was matched and the name in addr:street are not the same.

**Comment by matkoniecz** [comment]
`addr:street without correct road match`

> There always is a road match.

As implementation works - yes. But it can be also described as "QA found nearest street, has a different name, so it is not a match"

**Comment by lonvia** [comment]
How about 'Suspicious addr:street tag'?

**Comment by matkoniecz** [comment]
Also works

**Pull request merged**
